### ISSUE TITLE
Use default engine for resolving class specs for loggers as well

### ISSUE THREAD

**Issue by fdraxler** [LarsKue/lightning-trainable#11]
See https://github.com/LarsKue/lightning-trainable/blob/91b59a8e98f8fdd5b7073b6b9acff46cfeef948e/src/lightning_trainable/trainable/trainable.py#L280

**Comment by LarsKue** [comment]
Could you please elaborate what you mean with class specs?

**Comment by fdraxler** [comment]
Sure, I meant like `utils.get_scheduler(name)` for getting a learning rate scheduler. I don't think PT Lightning offers one package with most common loggers though…

**Comment by LarsKue** [comment]
Added in 41082fd
