### ISSUE TITLE
How to validate without logger?

### ISSUE THREAD

**Issue by fdraxler** [LarsKue/lightning-trainable#12]
After training, I would like to validate without the results being logged.

The following code produces a new log directory containing the result.
```python
# model.fit() already called
trainer = model.configure_trainer()
metrics = trainer.validate()
```

I can't set `configure_trainer(trainer_kwargs=dict(logger=False))` because `logger` is set automatically by `configure_trainer`

I'd suggest skipping `configure_logger` in `configure_trainer` if "`logger` in trainer_kwargs`. I am implementing it like this for now, but am happy for suggestions

**Comment by fdraxler** [comment]
The same might also apply to any other trainer_kwargs that we set to a default in `configure_trainer`. It could be useful to overwrite them from outside. Maybe setup our default values and update with the passed trainer_kwargs.

**Comment by fdraxler** [comment]
And the function should also deepcopy the passed `kwargs` as not to overwrite some external dictionary

**Comment by LarsKue** [comment]
Can you overwrite the logger on the trainer object before you call `trainer.validate()`?

**Comment by LarsKue** [comment]
2d467a755575ede3c0a500e13a000650bd41c048 introduces some changes to how the logger is set in `trainer_kwargs`. `configure_logger` is still called, but you can now override the `logger` arg that is passed to the `Trainer` instance. Let me know if you consider this a fix to this issue.

**Comment by fdraxler** [comment]
Cool, thanks!
