### ISSUE TITLE
omegaconf

### ISSUE THREAD

**Issue by ThisIsForReview** [LarsKue/lightning-trainable#26]
Hi Lars

I thought this information may be useful to you.   I figured it out why my initial installation of lightning-trainable was not working.

After tracing the code, I found that I have to remove my installed package OmegaConf, otherwise torch lightning will use omegaconf to save trainer parameters which may contradict to the definition of AttributeDict in lightning-trainable.

JB

**Comment by LarsKue** [comment]
Hi JB, thanks for the heads-up!
