### ISSUE TITLE
Progressbar confusing when continuing training of a loaded model.

### ISSUE THREAD

**Issue by HeiseMax** [LarsKue/lightning-trainable#8]
When continuing to train a model loaded from a checkpoint it will train for {max_epochs - "already trained epochs"}.

Example:

- Loaded model already trained 200 epochs.
- max_epochs = 400
- => training will be 200 epochs

![Screenshot from 2023-05-30 10-34-14](https://github.com/LarsKue/lightning-trainable/assets/71936191/e2ed3870-4531-48ee-ac6c-7d1900c7208e)
The epoch counter on the left shows total trained epochs. The counter on the right shows trained epochs in the current run, but the total on the right is max_epochs although training will only be half of that. 

When the training is finished the progressbar is only at the halfway line.
![Screenshot from 2023-05-30 11-00-41](https://github.com/LarsKue/lightning-trainable/assets/71936191/9e826faf-9fe0-4318-a457-610c463d5c16)
(Sorry, different example.)

**Comment by LarsKue** [comment]
Reverted to the default lightning progress bar for now.
